import { useEffect, useMemo, useState } from "react";
import { Activity, CalendarDays, Check, ChefHat, Clock3, Heart, Home, LockKeyhole, Search, Settings, ShoppingBag, Timer, Trash2, UtensilsCrossed } from "lucide-react";

type Page="dashboard"|"today"|"recipes"|"workouts"|"shop"|"settings";
type WorkoutDone={id:string;day:string;name:string};
type Recipe={id:string;name:string;category:string;time:number;cal:number;protein:number;carbs:number;free?:boolean;emoji:string;ingredients:string[];steps:string[];allergens:string[]};
type Planned={id:string;recipeId:string;day:string;cooked:boolean};
const R=(id:string,name:string,category:string,time:number,cal:number,protein:number,carbs:number,emoji:string,free=false,ingredients:string[]=[],steps:string[]=[],allergens:string[]=[]):Recipe=>({id,name,category,time,cal,protein,carbs,emoji,free,ingredients,steps,allergens});
const recipes:Recipe[]=[
R("f1","Berry Overnight Oats","Breakfast",10,310,14,49,"🫐",true,["1/2 cup rolled oats","3/4 cup milk","1/2 cup blueberries","1 tsp honey"],["Combine oats and milk in a jar.","Refrigerate overnight.","Top with blueberries and honey."],["Milk"]),
R("f2","Spinach Egg Toast","Breakfast",15,330,22,27,"🍳",true,["2 eggs","2 slices whole wheat bread","2 cups spinach","1 tsp olive oil"],["Toast the bread.","Wilt spinach in olive oil.","Scramble eggs and serve over toast."],["Eggs","Wheat"]),
R("f3","Avocado Tomato Toast","Breakfast",10,295,9,36,"🥑",true,["2 slices whole wheat bread","1/2 avocado","1 tomato","1 tsp lemon juice"],["Toast bread.","Mash avocado with lemon.","Add tomato slices and season."],["Wheat"]),
R("f4","Protein Banana Pancakes","Breakfast",15,340,24,42,"🥞",true,["1 banana","2 eggs","1/2 cup oats","1/2 cup Greek yogurt"],["Blend banana, eggs and oats.","Cook small pancakes on a nonstick skillet.","Serve with yogurt."],["Eggs","Milk"]),
R("f5","Chicken Rice Bowl","Lunch",30,510,46,48,"🍚",true,["5 oz chicken breast","3/4 cup cooked rice","1 cup broccoli","1 tsp olive oil"],["Season and grill chicken.","Steam broccoli.","Serve chicken over rice with broccoli."],[]),
R("f6","Chickpea Lemon Salad","Lunch",15,390,16,52,"🥗",true,["1 cup chickpeas","1/2 cucumber","1 tomato","1 tbsp olive oil","1 tbsp lemon juice"],["Drain chickpeas.","Dice vegetables.","Toss everything with lemon and olive oil."],[]),
R("f7","Turkey Avocado Wrap","Lunch",12,430,35,39,"🌯",true,["1 whole wheat tortilla","4 oz turkey breast","1/2 avocado","lettuce","tomato"],["Warm tortilla.","Layer turkey and vegetables.","Add avocado and roll tightly."],["Wheat"]),
R("f8","Lentil Vegetable Soup","Dinner",35,360,21,55,"🥣",true,["1 cup cooked lentils","1 carrot","1 celery stalk","1 cup tomatoes","2 cups vegetable broth"],["Sauté chopped vegetables.","Add lentils, tomatoes and broth.","Simmer until vegetables are tender."],[]),
R("f9","Salmon Sweet Potato Plate","Dinner",30,520,39,45,"🐟",true,["5 oz salmon","1 medium sweet potato","1 cup green beans","1 tsp olive oil"],["Roast sweet potato.","Bake seasoned salmon.","Steam beans and serve together."],["Fish"]),
R("f10","Greek Yogurt Berry Cup","Afternoon Snack",5,230,20,28,"🍓",true,["1 cup Greek yogurt","1/2 cup berries","1 tbsp chia seeds","1 tsp honey"],["Add yogurt to a bowl.","Top with berries, chia and honey."],["Milk"]),
R("f11","Apple Peanut Butter Oats","Afternoon Snack",8,285,10,43,"🍎",true,["1/2 cup oats","1 apple","1 tbsp peanut butter","cinnamon"],["Cook oats with water or milk.","Dice apple.","Top oats with apple, peanut butter and cinnamon."],["Peanuts"]),
R("f12","Berry Protein Smoothie","Afternoon Snack",5,280,25,34,"🥤",true,["1 cup frozen berries","1 scoop protein powder","1 cup milk","1/2 banana"],["Add all ingredients to a blender.","Blend until smooth and serve cold."],["Milk"]),
R("p1","Banana Oat Cake","Healthy Cakes",40,220,8,36,"🍰",false,["2 ripe bananas","2 cups rolled oats","2 eggs","1 tsp baking powder","1 tsp cinnamon"],["Heat oven to 350°F.","Blend oats into flour and mix with remaining ingredients.","Bake in a lined pan for 28–32 minutes."],["Eggs"]),
R("p2","Apple Cinnamon Oat Cake","Healthy Cakes",45,205,7,35,"🍏",false,["1 apple","2 cups oat flour","2 eggs","3/4 cup milk","1 tsp cinnamon"],["Heat oven to 350°F.","Fold diced apple into the batter.","Bake until the center is set."],["Eggs","Milk"]),
R("p3","Cocoa Banana Cake","Healthy Cakes",40,215,8,34,"🍫",false,["2 bananas","1 3/4 cups oat flour","2 eggs","1/4 cup cocoa powder"],["Mash bananas.","Whisk with eggs and dry ingredients.","Bake at 350°F for about 30 minutes."],["Eggs"]),
R("p4","Carrot Oat Cake","Healthy Cakes",45,210,7,33,"🥕",false,["1 cup grated carrot","2 cups oat flour","2 eggs","3/4 cup yogurt","cinnamon"],["Combine wet ingredients.","Fold in carrot and oat flour.","Bake at 350°F until golden."],["Eggs","Milk"]),
R("p5","Yogurt Lemon Cake","Healthy Cakes",42,195,9,31,"🍋",false,["1 cup Greek yogurt","2 eggs","1 3/4 cups oat flour","1 lemon"],["Zest and juice lemon.","Mix all ingredients into a smooth batter.","Bake at 350°F for 30–35 minutes."],["Eggs","Milk"]),
R("p6","Whole Wheat Sandwich Bread","Fitness Breads",70,145,6,27,"🍞",false,["3 cups whole wheat flour","1 cup warm water","2 tsp yeast","1 tbsp olive oil"],["Activate yeast in warm water.","Knead dough until elastic and let rise.","Bake at 375°F until browned."],["Wheat"]),
R("p7","Oat Banana Breakfast Bread","Fitness Breads",55,180,7,34,"🍌",false,["2 bananas","2 cups oat flour","2 eggs","1/2 cup milk"],["Mash bananas.","Mix with eggs, milk and oat flour.","Bake at 350°F until set."],["Eggs","Milk"]),
R("p8","Whole Wheat Herb Rolls","Fitness Breads",65,155,6,28,"🌿",false,["2 1/2 cups whole wheat flour","1 cup warm water","2 tsp yeast","mixed herbs"],["Make and knead dough.","Shape into rolls and proof.","Bake at 375°F until golden."],["Wheat"]),
R("p9","Sweet Potato Bread","Fitness Breads",55,175,6,32,"🍠",false,["1 cup mashed sweet potato","2 cups whole wheat flour","2 eggs","1 tsp baking powder"],["Combine sweet potato and eggs.","Fold in dry ingredients.","Bake at 350°F until a tester comes out clean."],["Eggs","Wheat"]),
R("p10","Skillet Oat Bread","Fitness Breads",25,165,8,27,"🥖",false,["1 cup oat flour","1 egg","1/2 cup Greek yogurt","1 tsp baking powder"],["Mix into a thick batter.","Spread in a lightly greased skillet.","Cook covered on low, flip and finish."],["Eggs","Milk"])
];
const nav=[["dashboard","Dashboard",Home],["today","What to Eat Today",CalendarDays],["recipes","Recipes",ChefHat],["workouts","Workouts",Activity],["shop","Shop",ShoppingBag],["settings","Settings",Settings]] as const;
const load=<T,>(k:string,d:T):T=>{try{return JSON.parse(localStorage.getItem(k)||"") as T}catch{return d}};
export default function App(){
 const[page,setPage]=useState<Page>("dashboard"); const[favs,setFavs]=useState<string[]>(()=>load("sg-favs",[])); const[unlocked,setUnlocked]=useState<string[]>(()=>load("sg-unlocked",[])); const[plan,setPlan]=useState<Planned[]>(()=>load("sg-plan",[])); const[workouts,setWorkouts]=useState<WorkoutDone[]>(()=>load("sg-workouts",[])); const[selected,setSelected]=useState<Recipe|null>(null);
 useEffect(()=>localStorage.setItem("sg-favs",JSON.stringify(favs)),[favs]); useEffect(()=>localStorage.setItem("sg-unlocked",JSON.stringify(unlocked)),[unlocked]); useEffect(()=>localStorage.setItem("sg-plan",JSON.stringify(plan)),[plan]); useEffect(()=>localStorage.setItem("sg-workouts",JSON.stringify(workouts)),[workouts]);
 const title=nav.find(n=>n[0]===page)?.[1]??"Smart Grocery";
 return <div className="app"><aside><div className="brand"><span>SG</span><div>SMART<br/><b>GROCERY</b></div></div><nav>{nav.map(([id,label,Icon])=><button className={page===id?"active":""} onClick={()=>setPage(id)} key={id}><Icon size={19}/>{label}</button>)}</nav><div className="sideNote"><ChefHat size={18}/><b>12 free recipes</b><small>Build your collection your way.</small></div></aside><main><header><div><small>SMART GROCERY US</small><h1>{title}</h1></div><div className="avatar">K</div></header>
 {page==="dashboard"&&<Dashboard plan={plan} workouts={workouts} favs={favs.length}/>}
 {page==="today"&&<Today plan={plan} setPlan={setPlan} open={setSelected}/>}
 {page==="recipes"&&<Recipes favs={favs} setFavs={setFavs} unlocked={unlocked} plan={plan} setPlan={setPlan} open={setSelected}/>}\n {page==="workouts"&&<Workouts done={workouts} setDone={setWorkouts}/>}
 {page==="shop"&&<Shop unlocked={unlocked} setUnlocked={setUnlocked}/>}
 {page==="settings"&&<SettingsPage/>}
 </main><div className="mobileNav">{nav.map(([id,,Icon])=><button className={page===id?"active":""} onClick={()=>setPage(id)} key={id}><Icon size={20}/></button>)}</div>
 {selected&&<RecipeModal recipe={selected} unlocked={selected.free||unlocked.includes(selected.id)} close={()=>setSelected(null)} add={()=>{setPlan(p=>[...p,{id:crypto.randomUUID(),recipeId:selected.id,day:new Date().toISOString().slice(0,10),cooked:false}]);setSelected(null)}}/>}</div>
}
function Dashboard({plan,workouts,favs}:{plan:Planned[];workouts:WorkoutDone[];favs:number}){const cooked=plan.filter(x=>x.cooked);const days=new Set([...cooked.map(x=>x.day),...workouts.map(x=>x.day)]).size;return <><section className="hero"><div><span className="eyebrow">YOUR HEALTHY ROUTINE</span><h2>Eat smarter.<br/><em>Feel stronger.</em></h2><p>Plan healthy meals, discover fitness recipes and keep your week moving.</p></div><div className="heroPlate">🥗<span>12<br/><b>FREE</b></span></div></section><div className="stats">{[["Meals Prepared",cooked.length,UtensilsCrossed],["Workouts",workouts.length,Activity],["Active Days",days,Activity],["Favorites",favs,Heart]].map(([a,b,I]:any)=><div className="stat" key={a}><I size={20}/><small>{a}</small><strong>{b}</strong></div>)}</div><section className="panel"><div className="sectionHead"><div><small>THIS WEEK</small><h3>Weekly Progress</h3></div><span>{cooked.length+workouts.length} activities</span></div>{cooked.length+workouts.length?<div className="progressList">{[...cooked.map(x=>({id:x.id,name:recipes.find(r=>r.id===x.recipeId)?.name||"Meal",day:x.day})),...workouts].slice(-5).reverse().map(x=><div key={x.id}><Check size={17}/><span>{x.name}</span><b>{x.day}</b></div>)}</div>:<div className="emptyChart"><Activity size={28}/><b>Your progress starts here</b><p>Mark a planned meal as prepared and your progress will appear here.</p></div>}</section></>}
function Today({plan,setPlan,open}:{plan:Planned[];setPlan:(x:Planned[])=>void;open:(r:Recipe)=>void}){return <><section className="intro"><span className="eyebrow">MY PLANNING</span><h2>What are you eating today?</h2><p>Your saved meals in one simple place. Mark them prepared when you're done.</p></section><section className="panel"><div className="sectionHead"><h3>My Planning</h3><span>{plan.length} meals</span></div>{!plan.length?<div className="empty"><CalendarDays/><b>No meals planned yet</b><p>Open an unlocked recipe and add it to your planning.</p></div>:<div className="planList">{plan.map(p=>{const r=recipes.find(x=>x.id===p.recipeId)!;return <div className={"planRow "+(p.cooked?"done":"")} key={p.id} onClick={()=>open(r)}><div className="planEmoji">{r.emoji}</div><div><small>{p.day} · {r.category}</small><b>{r.name}</b><span><Clock3 size={13}/>{r.time} min · {r.cal} kcal · {r.protein}g protein</span></div><button title="Prepared" onClick={e=>{e.stopPropagation();setPlan(plan.map(x=>x.id===p.id?{...x,cooked:!x.cooked}:x))}}><Check/></button><button title="Remove" onClick={e=>{e.stopPropagation();setPlan(plan.filter(x=>x.id!==p.id))}}><Trash2/></button></div>})}</div>}</section></>}
function Recipes({favs,setFavs,unlocked,plan,setPlan,open}:{favs:string[];setFavs:(x:string[])=>void;unlocked:string[];plan:Planned[];setPlan:(x:Planned[])=>void;open:(r:Recipe)=>void}){const[q,setQ]=useState("");const[filter,setFilter]=useState("All");const filtered=recipes.filter(r=>r.name.toLowerCase().includes(q.toLowerCase())&&(filter==="All"||filter==="Favorites"&&favs.includes(r.id)||filter==="Unlocked"&&(r.free||unlocked.includes(r.id))||r.category===filter));return <><section className="intro"><span className="eyebrow">HEALTHY, NOT BORING</span><h2>Recipes for your routine.</h2><p>12 recipes are free. Unlock additional recipes individually or with recipe packs.</p></section><div className="search"><Search size={18}/><input placeholder="Search recipes..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="chips">{["All","Favorites","Unlocked","Breakfast","Lunch","Dinner","Afternoon Snack","Healthy Cakes","Fitness Breads"].map(x=><button className={filter===x?"selected":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="recipeGrid">{filtered.map(r=>{const access=r.free||unlocked.includes(r.id);return <article className="recipe" key={r.id}><div className="food" onClick={()=>access&&open(r)}>{r.emoji}<button className="heart" onClick={e=>{e.stopPropagation();setFavs(favs.includes(r.id)?favs.filter(x=>x!==r.id):[...favs,r.id])}}><Heart size={18} fill={favs.includes(r.id)?"currentColor":"none"}/></button>{r.free?<span className="freeTag">FREE</span>:!access?<span className="lock"><LockKeyhole size={14}/> $2.00</span>:<span className="freeTag">UNLOCKED</span>}</div><div className="recipeBody"><small>{r.category}</small><h3>{r.name}</h3><div className="macros"><span><Timer size={14}/>{r.time} min</span><span>{r.cal} kcal</span></div><div className="macroLine"><span><b>{r.protein}g</b> Protein</span><span><b>{r.carbs}g</b> Carbs</span></div>{access?<button className="cardAction" onClick={()=>open(r)}>View recipe</button>:<button className="cardAction locked">Unlock · $2.00</button>}</div></article>})}</div></>}

function Workouts({done,setDone}:{done:WorkoutDone[];setDone:(x:WorkoutDone[])=>void}){const[place,setPlace]=useState("Gym");const[level,setLevel]=useState("Beginner");const[goal,setGoal]=useState("Lose Weight");const plans:{[k:string]:string[]}={Gym:["Goblet Squat · 3 × 10","Chest Press · 3 × 10","Lat Pulldown · 3 × 12","Romanian Deadlift · 3 × 10","Incline Walk · 12 min"],Home:["Bodyweight Squat · 3 × 15","Push-ups · 3 × 8–12","Reverse Lunges · 3 × 10/side","Glute Bridge · 3 × 15","Mountain Climbers · 3 × 30 sec"]};const name=`${place} · ${goal} · ${level}`;const today=new Date().toISOString().slice(0,10);const completed=done.some(x=>x.day===today&&x.name===name);return <><section className="intro"><span className="eyebrow">TRAIN YOUR WAY</span><h2>Workout Program</h2><p>Choose your goal, training location and experience level to build today's routine.</p></section><div className="workoutControls"><label>Goal<select value={goal} onChange={e=>setGoal(e.target.value)}><option>Lose Weight</option><option>Maintain</option><option>Gain Muscle</option></select></label><label>Location<select value={place} onChange={e=>setPlace(e.target.value)}><option>Gym</option><option>Home</option></select></label><label>Level<select value={level} onChange={e=>setLevel(e.target.value)}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label></div><section className="panel workoutCard"><div className="sectionHead"><div><small>TODAY'S WORKOUT</small><h3>{name}</h3></div><span>{place==="Gym"?"GYM":"HOME"}</span></div><div className="exerciseList">{plans[place].map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span></div>)}</div><button className="primary" disabled={completed} onClick={()=>!completed&&setDone([...done,{id:crypto.randomUUID(),day:today,name}])}>{completed?"Workout completed ✓":"Complete Workout"}</button><p className="disclaimer">Adjust load, range of motion and exercise selection to your ability. Stop if you feel pain. This routine is general fitness information, not medical advice.</p></section></>}
function Shop({unlocked,setUnlocked}:{unlocked:string[];setUnlocked:(x:string[])=>void}){const packs=[["1 Recipe","$2.00",1],["3 Recipes","$5.50",3],["5 Recipes","$8.50",5],["10 Recipes","$15.00",10],["20 Recipes","$27.00",20]] as const;const locked=recipes.filter(r=>!r.free&&!unlocked.includes(r.id));return <><section className="intro"><span className="eyebrow">RECIPE SHOP</span><h2>More recipes. Better value.</h2><p>No subscription required. Choose individual recipes or save with a pack.</p></section><div className="packGrid">{packs.map((p,i)=><div className={"pack "+(i===3?"featured":"")} key={p[0]}>{i===3&&<span className="best">POPULAR</span>}<ShoppingBag/><h3>{p[0]}</h3><strong>{p[1]}</strong><p>One-time purchase</p><button className="secondary" onClick={()=>{const next=locked.slice(0,p[2]).map(r=>r.id);setUnlocked([...new Set([...unlocked,...next])])}}>Simulate unlock</button></div>)}</div><section className="panel shopInfo"><h3>How recipe packs work</h3><p>After checkout is connected, a pack will give you recipe credits. You'll choose exactly which premium recipes you want to unlock. The buttons above currently simulate that flow for testing.</p></section></>}
function RecipeModal({recipe,unlocked,close,add}:{recipe:Recipe;unlocked:boolean;close:()=>void;add:()=>void}){return <div className="modalBack" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={close}>×</button><div className="modalFood">{recipe.emoji}</div><span className="eyebrow">{recipe.category}</span><h2>{recipe.name}</h2><div className="detailMacros"><span>{recipe.cal}<small>kcal</small></span><span>{recipe.protein}g<small>protein</small></span><span>{recipe.carbs}g<small>carbs</small></span><span>{recipe.time}<small>minutes</small></span></div>{unlocked?<><h3>Ingredients</h3><ul>{recipe.ingredients.map(x=><li key={x}>{x}</li>)}</ul><h3>Preparation</h3><ol>{recipe.steps.map(x=><li key={x}>{x}</li>)}</ol><h3>Allergens</h3><p>{recipe.allergens.length?recipe.allergens.join(", "):"No major allergens identified from the listed ingredients."}</p><button className="primary" onClick={add}>Add to My Planning</button></>:<><div className="lockedDetail"><LockKeyhole/><b>Premium recipe</b><p>Unlock this recipe to see the full ingredients and preparation.</p><strong>$2.00</strong></div></>}</div></div>}
function SettingsPage(){return <section className="panel settings"><h3>Preferences</h3><label>Language<input value="English (US)" disabled/></label><label>Currency<input value="USD ($)" disabled/></label><label>Measurements<input value="US customary" disabled/></label><p>Favorites, unlocked recipes and meal planning are saved locally on this device.</p><p className="disclaimer">Nutrition values are estimates for general informational purposes and are not medical or dietary advice.</p></section>}
